services:
  transfer:
    build: .
    image: chatwoot-orchestrator:latest
    environment:
      CHATWOOT_TOKEN: ${CHATWOOT_TOKEN}
      CHATWOOT_ACCOUNT_ID: ${CHATWOOT_ACCOUNT_ID}
      CHATWOOT_DOMAIN: ${CHATWOOT_DOMAIN}
      CHATWOOT_VERIFY_TLS: ${CHATWOOT_VERIFY_TLS}
    env_file: .env
    restart: always
