services:
  app:
    environment:
      CHATWOOT_TOKEN: ${CHATWOOT_TOKEN}
      CHATWOOT_ACCOUNT_ID: ${CHATWOOT_ACCOUNT_ID}
      CHATWOOT_DOMAIN: ${CHATWOOT_DOMAIN}
      CHATWOOT_VERIFY_TLS: true
    env_file: .env
    restart: always
